watchlist:
  a_share:
    - symbol: "002851"
      name: "麦格米特"
    - symbol: "301171"
      name: "易点天下"
    - symbol: "300124"
      name: "汇川技术"
    - symbol: "600089"
      name: "特变电工"
    - symbol: "601138"
      name: "工业富联"
    - symbol: "600487"
      name: "亨通光电"
    - symbol: "300750"
      name: "宁德时代"
    - symbol: "002594"
      name: "比亚迪"
